const express = require('express');
const dotenv = require("dotenv");
dotenv.config({ path: "./src/config/config.env" });
const port = process.env.PORT || 3000;
const app = express();
const connetDB = require('./src/config/db');
connetDB();
const bodyParser = require("body-parser");
app.use(bodyParser.json({ limit: "50mb" }));
app.use('/api/v2/user', require('./src/routes/user'));
app.listen(port, console.log(`Server is running on port ${port}`));